### ISSUE TITLE
dissmiss-stale-reviews VS dismiss_stale_reviews

### ISSUE THREAD

**Issue by taurus-forever** [roobre/reposettings#7]
HI,

There is a bit of inconsistency in naming here:
https://github.com/roobre/reposettings/blob/4622b897e769b3008bbcab99b68cf6cd5b90c02d/reposettings.py#L155

Should it be aligned to use `dismiss-stale-reviews` YAML config option too?

**Comment by roobre** [comment]
Hey,

Thanks for submitting this, that's indeed a spelling bug that should be squashed. I'll try to get that fixed asap.
